### ISSUE TITLE
编程式路由导航传递query参数，关闭页签时会报错。

### ISSUE THREAD

**Issue by wukai198786** [stepui/stepin-template#8]
问题：多tabs页签，使用编程式路由导航传递query参数，点击目标页签的[关闭图标]后会报错。(params参数正常)
错误代码：
`
// template
 <a-button size="small" type="primary" @click="goCtnPage(record)">
  
 // script
  const goCtnPage = (record) => {
    router.push({
      path: '/ctn',
      query: {
        plan_id: record.id,
      },
    });
  };

// 路由注册
  {
    path:'/ctn',
    name:'ctn',
    meta: {
      title:'箱管理',
      renderMenu: false,
    },
    component: () => import('@/pages/page-ctn/index.vue'),
  }
`
报错内容：
tabsView.js:283 行报错
main.ts:24 行报错
获的异常， TypeError: Cannot read properties of undefined (reading 'fullPath')
    at openOnClose (TabsView.js:306:40)
    at closeTab (TabsView.js:295:9)
    at createVNode.onClose._cache.<computed>._cache.<computed> (TabsView.js:747:18)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at emit (runtime-core.esm-bundler.js:730:9)
    at runtime-core.esm-bundler.js:7465:53
    at TabsViewHead.js:175:28
    at runtime-dom.esm-bundler.js:1483:16
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
a

**Comment by iczer** [comment]
已修复，参考提交： 735906095bf00d6d147dc5fb9c58774481113358。
同时，依赖库 stepin 更新至 2.1.38-beta，可直接执行 `yarn add stepin` 更新至最新版本
